# -*- coding: utf-8 -*-
"""
Generate Nuvu -> ThorCam_DMD -> DMD calibration using the shared SLM triangle.

Use case
--------
You generated an SLM triangle using the SLM/Fourier ThorCam coordinate system,
then observed the same three spots with the DMD-side ThorCam during DMD calibration.
This script uses that triangle as the bridge between the Nuvu coordinate system
and the DMD-side ThorCam/DMD coordinate systems.

Outputs
-------
1. slmsuite/calibration/nuvu_to_thorcam_slm.npz
2. dmdsuite/calibration/nuvu_to_thorcam_dmd.npz
3. dmdsuite/calibration/nv_chain_nuvu_thorcamDMD_dmd_1277.npz

Important
---------
Point ordering matters. The 3 DMD-side triangle points loaded from
triangle_affine_onpass.npz must correspond to OLD_TRIANGLE_THORCAM_SLM in the
same order. If not, change DMD_TRIANGLE_ORDER below.
"""

from __future__ import annotations

from pathlib import Path
import json

import cv2
import numpy as np
import matplotlib.pyplot as plt

from utils import common, kplotlib as kpl


# =============================================================================
# User-editable paths
# =============================================================================

NV_COORDS_PATH = "slmsuite/nv_blob_detection/nv_blob_1277nvs_reordered.npz"
DMD_TRIANGLE_CALIB_PATH = "dmdsuite/calibration/triangle_affine_onpass.npz"

NUVU_TO_THORCAM_SLM_OUT = "slmsuite/calibration/nuvu_to_thorcam_slm.npz"
NUVU_TO_THORCAM_DMD_OUT = "dmdsuite/calibration/nuvu_to_thorcam_dmd.npz"
DMD_CHAIN_OUT = "dmdsuite/calibration/nv_chain_nuvu_thorcamDMD_dmd_1277.npz"

# =============================================================================
# Known SLM-side Nuvu <-> ThorCam_SLM calibration from your SLM control panel
# =============================================================================

# These were in your nuvu2thorcam_calibration() function.
SLM_CAL_COORDS_THORCAM = np.array(
    [
        [883.205, 640.000],
        [536.795, 640.000],
        [710.000, 340.000],
    ],
    dtype=np.float32,
)

SLM_CAL_COORDS_NUVU = np.array(
    [
        [338.040, 361.354],
        [311.711,  11.032],
        [ 18.043, 209.580],
    ],
    dtype=np.float32,
)

# The SLM triangle generated by calibration_triangle(), in ThorCam_SLM coordinates.
# User log:
# thorcam coords: [[779.2820323 640.7179677 710.       ]
#                  [580.        580.        460.       ]]
# Converted here to Nx2: [[x0, y0], [x1, y1], [x2, y2]].
OLD_TRIANGLE_THORCAM_SLM = np.array(
    [
        [779.2820323, 580.0],
        [640.7179677, 580.0],
        [710.0000000, 460.0],
    ],
    dtype=np.float32,
)

# Reorder the DMD-side triangle points to match OLD_TRIANGLE_THORCAM_SLM.
# The DMD calibration detected points may be sorted by brightness, not by geometry.
# Start with [0, 1, 2]. If the diagnostic plot looks mismatched, change this.
# Example: [2, 0, 1] means:
#   old point 0 corresponds to tri_cam_pts[2]
#   old point 1 corresponds to tri_cam_pts[0]
#   old point 2 corresponds to tri_cam_pts[1]
# DMD_TRIANGLE_ORDER = [0, 1, 2]
DMD_TRIANGLE_ORDER = [2, 1, 0]

# =============================================================================
# Path helpers
# =============================================================================


def repo_path() -> Path:
    if common is not None:
        return Path(common.get_repo_path())
    # Fallback: assume script is run from repo root.
    return Path.cwd()


def resolve_path(path_like: str | Path) -> Path:
    p = Path(path_like)
    if p.is_absolute():
        return p
    return repo_path() / p


def ensure_parent(path_like: str | Path) -> Path:
    p = resolve_path(path_like)
    p.parent.mkdir(parents=True, exist_ok=True)
    return p


# =============================================================================
# Affine helpers
# =============================================================================


def apply_affine(M: np.ndarray, pts: np.ndarray) -> np.ndarray:
    pts = np.asarray(pts, dtype=np.float32).reshape(-1, 2)
    ones = np.ones((len(pts), 1), dtype=np.float32)
    return np.hstack([pts, ones]) @ np.asarray(M, dtype=np.float32).T


def invert_affine(M: np.ndarray) -> np.ndarray:
    return cv2.invertAffineTransform(np.asarray(M, dtype=np.float32))


def affine_2x3_to_3x3(M: np.ndarray) -> np.ndarray:
    H = np.eye(3, dtype=np.float32)
    H[:2, :] = np.asarray(M, dtype=np.float32)
    return H


def affine_3x3_to_2x3(H: np.ndarray) -> np.ndarray:
    return np.asarray(H, dtype=np.float32)[:2, :]


def fit_affine(src_pts: np.ndarray, dst_pts: np.ndarray) -> tuple[np.ndarray, np.ndarray | None, np.ndarray]:
    src_pts = np.asarray(src_pts, dtype=np.float32).reshape(-1, 2)
    dst_pts = np.asarray(dst_pts, dtype=np.float32).reshape(-1, 2)

    if len(src_pts) == 3:
        M = cv2.getAffineTransform(src_pts, dst_pts)
        inliers = np.ones((3, 1), dtype=np.uint8)
    else:
        M, inliers = cv2.estimateAffine2D(src_pts, dst_pts)
        if M is None:
            raise RuntimeError("Affine fit failed.")

    pred = apply_affine(M, src_pts)
    residuals = dst_pts - pred
    return M.astype(np.float32), inliers, residuals.astype(np.float32)


# =============================================================================
# Main generation
# =============================================================================


def load_nv_coords(path: str | Path) -> tuple[np.ndarray, np.ndarray | None, dict]:
    p = resolve_path(path)
    data = np.load(p, allow_pickle=True)

    nv_coords = np.asarray(data["nv_coordinates"], dtype=np.float32)
    spot_weights = None
    if "updated_spot_weights" in data.files:
        spot_weights = np.asarray(data["updated_spot_weights"], dtype=np.float32)

    extra = {"source_file": str(p), "keys": list(data.files)}
    return nv_coords, spot_weights, extra


def load_dmd_triangle(path: str | Path) -> dict:
    p = resolve_path(path)
    data = np.load(p, allow_pickle=True)
    out = {key: data[key] for key in data.files}
    out["source_file"] = str(p)
    return out


def plot_triangle_correspondence(tri_nuvu, tri_thorcam_dmd, tri_dmd, save_path=None):
    fig, axes = plt.subplots(1, 3, figsize=(13, 4))

    packs = [
        (tri_nuvu, "Triangle in Nuvu coords"),
        (tri_thorcam_dmd, "Same triangle in ThorCam_DMD coords"),
        (tri_dmd, "Same triangle in DMD coords"),
    ]

    for ax, (pts, title) in zip(axes, packs):
        pts = np.asarray(pts, dtype=np.float32)
        ax.plot(pts[:, 0], pts[:, 1], "o-")
        for i, (x, y) in enumerate(pts):
            ax.text(x + 3, y + 3, str(i))
        ax.set_title(title)
        ax.set_aspect("equal", adjustable="box")
        ax.set_xlabel("x")
        ax.set_ylabel("y")

    fig.tight_layout()
    if save_path is not None:
        fig.savefig(save_path, dpi=200)
        print(f"Saved diagnostic plot: {save_path}")
    return fig


def main():
    # -------------------------------------------------------------------------
    # 1. Build Nuvu -> ThorCam_SLM from existing known points.
    # -------------------------------------------------------------------------
    M_nuvu_to_thorcam_slm, _, residual_slm = fit_affine(
        SLM_CAL_COORDS_NUVU,
        SLM_CAL_COORDS_THORCAM,
    )
    M_thorcam_slm_to_nuvu = invert_affine(M_nuvu_to_thorcam_slm)

    print("M_nuvu_to_thorcam_slm:")
    print(M_nuvu_to_thorcam_slm)
    print("SLM calibration residuals [px]:")
    print(residual_slm)

    # Convert old SLM triangle ThorCam coords -> Nuvu coords.
    triangle_nuvu = apply_affine(M_thorcam_slm_to_nuvu, OLD_TRIANGLE_THORCAM_SLM)

    print("Triangle points inferred in Nuvu coords:")
    print(triangle_nuvu)

    # Save Nuvu -> ThorCam_SLM file.
    out_slm = ensure_parent(NUVU_TO_THORCAM_SLM_OUT)
    np.savez_compressed(
        out_slm,
        M_nuvu_to_thorcam_slm=M_nuvu_to_thorcam_slm,
        M_thorcam_slm_to_nuvu=M_thorcam_slm_to_nuvu,
        cal_coords_nuvu=SLM_CAL_COORDS_NUVU,
        cal_coords_thorcam_slm=SLM_CAL_COORDS_THORCAM,
        old_triangle_thorcam_slm=OLD_TRIANGLE_THORCAM_SLM,
        triangle_nuvu=triangle_nuvu,
        convention="NUVU_TO_THORCAM_SLM",
    )
    print(f"Saved: {out_slm}")

    # -------------------------------------------------------------------------
    # 2. Load DMD triangle calibration and reorder the DMD-side triangle points.
    # -------------------------------------------------------------------------
    dmd_tri = load_dmd_triangle(DMD_TRIANGLE_CALIB_PATH)

    tri_cam_pts_raw = np.asarray(dmd_tri["tri_cam_pts"], dtype=np.float32).reshape(-1, 2)
    tri_dmd_pts_raw = np.asarray(dmd_tri["tri_dmd_pts"], dtype=np.float32).reshape(-1, 2)

    order = np.asarray(DMD_TRIANGLE_ORDER, dtype=int)
    if sorted(order.tolist()) != [0, 1, 2]:
        raise ValueError("DMD_TRIANGLE_ORDER must be a permutation of [0, 1, 2].")

    triangle_thorcam_dmd = tri_cam_pts_raw[order]
    triangle_dmd = tri_dmd_pts_raw[order]

    print("DMD-side triangle raw tri_cam_pts:")
    print(tri_cam_pts_raw)
    print("DMD-side triangle reordered to match OLD_TRIANGLE_THORCAM_SLM:")
    print(triangle_thorcam_dmd)

    # -------------------------------------------------------------------------
    # 3. Fit Nuvu -> ThorCam_DMD from the shared triangle.
    # -------------------------------------------------------------------------
    M_nuvu_to_thorcam_dmd, _, residual_nuvu_to_dmd_cam = fit_affine(
        triangle_nuvu,
        triangle_thorcam_dmd,
    )

    M_thorcam_dmd_to_dmd = np.asarray(dmd_tri["M_cam_to_dmd"], dtype=np.float32)

    H_nuvu_to_thorcam_dmd = affine_2x3_to_3x3(M_nuvu_to_thorcam_dmd)
    H_thorcam_dmd_to_dmd = affine_2x3_to_3x3(M_thorcam_dmd_to_dmd)
    H_nuvu_to_dmd = H_thorcam_dmd_to_dmd @ H_nuvu_to_thorcam_dmd
    M_nuvu_to_dmd = affine_3x3_to_2x3(H_nuvu_to_dmd)

    print("M_nuvu_to_thorcam_dmd:")
    print(M_nuvu_to_thorcam_dmd)
    print("Triangle Nuvu -> ThorCam_DMD residuals [px]:")
    print(residual_nuvu_to_dmd_cam)
    print("M_nuvu_to_dmd:")
    print(M_nuvu_to_dmd)

    # Save Nuvu -> ThorCam_DMD file.
    out_nuvu_to_thorcam_dmd = ensure_parent(NUVU_TO_THORCAM_DMD_OUT)
    np.savez_compressed(
        out_nuvu_to_thorcam_dmd,
        M_nuvu_to_thorcam_dmd=M_nuvu_to_thorcam_dmd,
        M_thorcam_dmd_to_nuvu=invert_affine(M_nuvu_to_thorcam_dmd),
        triangle_nuvu=triangle_nuvu,
        triangle_thorcam_dmd=triangle_thorcam_dmd,
        old_triangle_thorcam_slm=OLD_TRIANGLE_THORCAM_SLM,
        raw_tri_cam_pts=tri_cam_pts_raw,
        raw_tri_dmd_pts=tri_dmd_pts_raw,
        dmd_triangle_order=order,
        residuals=residual_nuvu_to_dmd_cam,
        convention="NUVU_TO_THORCAM_DMD_FROM_SHARED_SLM_TRIANGLE",
    )
    print(f"Saved: {out_nuvu_to_thorcam_dmd}")

    # -------------------------------------------------------------------------
    # 4. Load all NVs and generate final DMD chain file.
    # -------------------------------------------------------------------------
    nv_coords_nuvu, spot_weights, nv_meta = load_nv_coords(NV_COORDS_PATH)
    nv_coords_thorcam_slm = apply_affine(M_nuvu_to_thorcam_slm, nv_coords_nuvu)
    nv_coords_thorcam_dmd = apply_affine(M_nuvu_to_thorcam_dmd, nv_coords_nuvu)
    nv_coords_dmd = apply_affine(M_nuvu_to_dmd, nv_coords_nuvu)

    out_chain = ensure_parent(DMD_CHAIN_OUT)
    np.savez_compressed(
        out_chain,
        # DMD server compatibility keys.
        M_cam_to_dmd=M_thorcam_dmd_to_dmd,
        zero_dmd_xy=np.asarray(dmd_tri["zero_dmd_xy"], dtype=np.float32),
        zero_cam_xy=np.asarray(dmd_tri["zero_cam_xy"], dtype=np.float32),
        dmd_points=nv_coords_dmd,
        pattern_dmd_points=nv_coords_dmd,
        pattern_camera_points=nv_coords_thorcam_dmd,
        slm_camera_points=nv_coords_thorcam_dmd,
        # Full chain keys.
        M_nuvu_to_thorcam_slm=M_nuvu_to_thorcam_slm,
        M_thorcam_slm_to_nuvu=M_thorcam_slm_to_nuvu,
        M_nuvu_to_thorcam_dmd=M_nuvu_to_thorcam_dmd,
        M_thorcam_dmd_to_dmd=M_thorcam_dmd_to_dmd,
        M_nuvu_to_dmd=M_nuvu_to_dmd,
        nv_coords_nuvu=nv_coords_nuvu,
        nv_coords_thorcam_slm=nv_coords_thorcam_slm,
        nv_coords_thorcam_dmd=nv_coords_thorcam_dmd,
        nv_coords_dmd=nv_coords_dmd,
        spot_weights=np.asarray([]) if spot_weights is None else spot_weights,
        triangle_nuvu=triangle_nuvu,
        triangle_thorcam_slm=OLD_TRIANGLE_THORCAM_SLM,
        triangle_thorcam_dmd=triangle_thorcam_dmd,
        triangle_dmd=triangle_dmd,
        dmd_triangle_order=order,
        source_nv_coords_path=nv_meta["source_file"],
        source_dmd_triangle_calib_path=dmd_tri["source_file"],
        convention="NUVU_TO_THORCAM_DMD_TO_DMD_FROM_SHARED_SLM_TRIANGLE",
    )
    print(f"Saved: {out_chain}")
    print(f"Number of NV DMD points: {len(nv_coords_dmd)}")

    # Diagnostic plot.
    diag_path = out_chain.with_suffix(".triangle_diagnostic.png")
    plot_triangle_correspondence(triangle_nuvu, triangle_thorcam_dmd, triangle_dmd, save_path=diag_path)
    # print("\nNext test in LabRAD:")
    # print(f'  dmd.load_calibration("{DMD_CHAIN_OUT}")')
    # print('  dmd.pass_loaded_indices("[0, 1, 2, 3, 4]", 20, 230)')
    # print('  dmd.block_loaded_indices("[0, 1, 2, 3, 4]", 20, 230)')


# if __name__ == "__main__":
#     kpl.init_kplotlib()
#     main()
#     kpl.show(block=True)



import itertools
import numpy as np
import cv2
import matplotlib.pyplot as plt


def apply_affine(M, pts):
    pts = np.asarray(pts, dtype=np.float32)
    if pts.ndim == 1:
        pts = pts[None, :]
    ones = np.ones((len(pts), 1), dtype=np.float32)
    pts_h = np.hstack([pts, ones])
    return pts_h @ M.T


# Old SLM-side ThorCam triangle, in the printed order
tri_slm_cam = np.array(
    [
        [779.2820323, 580.0],
        [640.7179677, 580.0],
        [710.0,       460.0],
    ],
    dtype=np.float32,
)

# Use the Fourier-calibration zero order / b point from your printout
zero_slm_cam = np.array([705.05789009, 519.93369574], dtype=np.float32)

# Load DMD triangle calibration
cal = np.load("dmdsuite/calibration/triangle_affine_onpass.npz", allow_pickle=True)

tri_dmd_cam_raw = np.asarray(cal["tri_cam_pts"], dtype=np.float32)
zero_dmd_cam = np.asarray(cal["zero_cam_xy"], dtype=np.float32).reshape(2)

best = None
results = []

for perm in itertools.permutations(range(3)):
    # Reorder DMD-side triangle to correspond to old SLM-side triangle order
    tri_dmd_cam = tri_dmd_cam_raw[list(perm)]

    # Fit ThorCam_SLM triangle -> ThorCam_DMD triangle
    M_slmcam_to_dmdcam = cv2.getAffineTransform(
        tri_slm_cam.astype(np.float32),
        tri_dmd_cam.astype(np.float32),
    )

    # Predict where old zero order should land on DMD ThorCam
    pred_zero_dmd_cam = apply_affine(M_slmcam_to_dmdcam, zero_slm_cam)[0]

    zero_err = np.linalg.norm(pred_zero_dmd_cam - zero_dmd_cam)

    results.append((perm, zero_err, pred_zero_dmd_cam, M_slmcam_to_dmdcam))

    if best is None or zero_err < best[1]:
        best = results[-1]

print("\nPermutation test:")
for perm, err, pred_zero, _ in results:
    print(f"perm={perm}, zero-order error = {err:.2f} px, pred_zero={pred_zero}")

best_perm, best_err, best_pred_zero, best_M = best

print("\nBEST:")
print("DMD_TRIANGLE_ORDER =", list(best_perm))
print("zero-order error [px] =", best_err)
print("predicted zero on DMD ThorCam =", best_pred_zero)
print("actual zero on DMD ThorCam    =", zero_dmd_cam)


# path = "dmdsuite/calibration/nv_chain_nuvu_thorcamDMD_dmd_1277.npz"
# data = np.load(path, allow_pickle=True)

# dmd_pts = data["dmd_points"]

# print("shape:", dmd_pts.shape)
# print("x min/max:", np.min(dmd_pts[:, 0]), np.max(dmd_pts[:, 0]))
# print("y min/max:", np.min(dmd_pts[:, 1]), np.max(dmd_pts[:, 1]))

# DMD_WIDTH = 1920
# DMD_HEIGHT = 1080

# inside = (
#     (dmd_pts[:, 0] >= 0)
#     & (dmd_pts[:, 0] < DMD_WIDTH)
#     & (dmd_pts[:, 1] >= 0)
#     & (dmd_pts[:, 1] < DMD_HEIGHT)
# )

# print("inside DMD:", np.sum(inside), "/", len(dmd_pts))
# print("outside indices:", np.where(~inside)[0][:50])